.\" Copyright (C) 2010 Julian Andres Klode. Released under the terms of the
.\" GNU General Public License, version 3 or later
.TH update-software-center 8 "2010-02-05" "1.1.10"
.SH NAME
update-software-center \- Update the database for software-center
.SH SYNOPSIS
.B update-software-center
.RI [ options ]
.SH DESCRIPTION
.B update-software-center
updates the database used by software-center.
.SH OPTIONS
.TP
.B \-h or \-\-help
print quick usage details to the screen.
.TP
.B \-\-triggered=TRIGGERED
passed when the command is triggered by dpkg.
.TP
.B \-\-debug
show debug output
.SH AUTHOR
This manpage has been written by Julian Andres Klode <jak@debian.org>.
